# Generated by Django 3.0.8 on 2020-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('facebook_link', models.URLField(max_length=150)),
                ('twitter_link', models.URLField(max_length=150)),
                ('linked_in', models.URLField(max_length=150)),
                ('instagram_link', models.URLField(max_length=150)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
